# Generated by Django 5.0.2 on 2024-03-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speci_name', models.CharField(max_length=50)),
            ],
        ),
    ]
