# Generated by Django 5.0.2 on 2024-03-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_tbl_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=50)),
            ],
        ),
    ]
