# Generated by Django 5.0.2 on 2024-04-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0005_tbl_aadhar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_aadhar',
        ),
    ]
