# Generated by Django 5.0.2 on 2024-03-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_tbl_facility'),
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_roomDetails',
            new_name='tbl_room',
        ),
    ]
