# Generated by Django 5.0.2 on 2024-03-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_tbl_facility'),
        ('Hotel', '0002_rename_tbl_roomdetails_tbl_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_room',
            new_name='tbl_roomdetails',
        ),
        migrations.RenameField(
            model_name='tbl_roomdetails',
            old_name='room_type',
            new_name='roomdetails_amount',
        ),
        migrations.RenameField(
            model_name='tbl_roomdetails',
            old_name='room_amount',
            new_name='roomdetails_count',
        ),
        migrations.RenameField(
            model_name='tbl_roomdetails',
            old_name='room_count',
            new_name='roomdetails_floor',
        ),
        migrations.RenameField(
            model_name='tbl_roomdetails',
            old_name='room_floor',
            new_name='roomdetails_occupancy',
        ),
        migrations.RenameField(
            model_name='tbl_roomdetails',
            old_name='room_occupancy',
            new_name='roomdetails_type',
        ),
    ]
