# Generated by Django 5.0.2 on 2024-03-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_rename_tbl_room_tbl_roomdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_roomdetails',
            old_name='room',
            new_name='roomtype',
        ),
        migrations.RemoveField(
            model_name='tbl_roomdetails',
            name='roomdetails_type',
        ),
    ]
