# Generated by Django 5.0.2 on 2024-03-19 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_tbl_newhotel'),
        ('Hotel', '0004_rename_room_tbl_roomdetails_roomtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_roomdetails',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newhotel'),
        ),
    ]
