# Generated by Django 5.0.2 on 2024-03-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_tbl_hotelfacility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_hotelfacility',
        ),
    ]
