# Generated by Django 5.0.2 on 2024-03-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_rename_room_type_tbl_roomtype_roomtype_type'),
        ('Guest', '0016_tbl_newhotel'),
        ('Hotel', '0007_delete_tbl_hotelfacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hotelfacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelfacility_name', models.CharField(max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_facility')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newhotel')),
            ],
        ),
    ]
