# Generated by Django 5.0.2 on 2024-03-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_tbl_newhotel'),
        ('Hotel', '0011_tbl_pickanddrophead'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newhotel')),
            ],
        ),
    ]
