# Generated by Django 5.0.2 on 2024-03-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0012_tbl_floor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_floor',
        ),
    ]
