# Generated by Django 5.0.2 on 2024-04-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0013_delete_tbl_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_hotelfacility',
            name='facility',
        ),
    ]
