# Generated by Django 5.0.2 on 2024-04-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0016_rename_speci_tbl_specialized_specialized_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_specialized',
            old_name='specialized_name',
            new_name='speci',
        ),
    ]
