# Generated by Django 5.0.4 on 2024-04-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0017_rename_specialized_name_tbl_specialized_speci'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_room_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_photo', models.FileField(upload_to='Room_Photos/')),
                ('room_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
