# Generated by Django 5.0.4 on 2024-04-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0018_tbl_room_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_room_description',
        ),
    ]
