# Generated by Django 5.0.2 on 2024-03-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_newuser',
            old_name='user_address',
            new_name='user_addr',
        ),
    ]
