# Generated by Django 5.0.2 on 2024-03-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_rename_user_address_tbl_newuser_user_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_newuser',
            old_name='user_addr',
            new_name='u_addr',
        ),
    ]
