# Generated by Django 5.0.2 on 2024-03-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_newhotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_newuser',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_newhotel',
        ),
        migrations.DeleteModel(
            name='tbl_newuser',
        ),
    ]
