# Generated by Django 5.0.2 on 2024-03-16 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0003_tbl_facility'),
        ('Guest', '0005_remove_tbl_newuser_place_delete_tbl_newhotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newhotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_ratings', models.CharField(max_length=50)),
                ('hotel_contact', models.CharField(max_length=50)),
                ('hotel_email', models.CharField(max_length=50)),
                ('hotel_pass', models.CharField(max_length=50)),
                ('hotel_addr', models.CharField(max_length=50)),
                ('hotel_vstatus', models.CharField(max_length=50)),
                ('hotel_photo', models.CharField(max_length=50)),
                ('hotel_license', models.CharField(max_length=50)),
                ('hotel_floor', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
                ('speci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_specification')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('user_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('user_status', models.IntegerField(default='0')),
                ('user_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
