# Generated by Django 5.0.2 on 2024-03-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newhotel',
        ),
    ]
