# Generated by Django 5.0.2 on 2024-03-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_tbl_facility'),
        ('Guest', '0011_delete_tbl_newhotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newhotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_ratings', models.CharField(max_length=50)),
                ('hotel_contact', models.CharField(max_length=50)),
                ('hotel_email', models.CharField(max_length=50)),
                ('hotel_pass', models.CharField(max_length=50)),
                ('hotel_addr', models.CharField(max_length=50)),
                ('hotel_vstatus', models.IntegerField(default='0')),
                ('hotel_photo', models.FileField(upload_to='Assets/HotelPhoto/')),
                ('hotel_license', models.CharField(max_length=50)),
                ('hotel_proof', models.FileField(upload_to='Assets/HotelProof/')),
                ('hotel_floor', models.CharField(max_length=50)),
                ('hotel_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
