# Generated by Django 5.0.2 on 2024-03-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0014_tbl_newhotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newhotel',
        ),
    ]
