# Generated by Django 5.0.2 on 2024-04-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0017_tbl_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_newhotel',
            name='hotel_floor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
