# Generated by Django 5.0.4 on 2024-04-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_alter_tbl_newhotel_hotel_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_newhotel',
            name='hotel_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
