# Generated by Django 5.0.4 on 2024-04-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_tbl_aadhar'),
        ('Guest', '0019_tbl_newhotel_hotel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_newhotel',
            name='hotel_spe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Administrator.tbl_specification'),
        ),
    ]
