# Generated by Django 5.0.4 on 2024-04-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0021_rename_hotel_spe_tbl_newhotel_speci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_newhotel',
            old_name='speci',
            new_name='hotel_spe',
        ),
    ]
