# Generated by Django 5.0.2 on 2024-04-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_tbl_booking_mealpackages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_occupants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupants_name', models.CharField(max_length=50)),
                ('occupants_dob', models.DateField()),
                ('occupants_gender', models.CharField(max_length=50)),
                ('occupants_contact', models.CharField(max_length=50)),
                ('occupantsr_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('occupants_aadhar', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
            ],
        ),
    ]
