# Generated by Django 5.0.2 on 2024-04-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_occupants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_occupants',
            old_name='occupantsr_proof',
            new_name='occupants_proof',
        ),
    ]
