# Generated by Django 5.0.2 on 2024-04-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_remove_tbl_booking_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_occupants',
            name='booking',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_occupants',
        ),
    ]
