# Generated by Django 5.0.2 on 2024-04-06 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_alter_tbl_newhotel_hotel_floor'),
        ('User', '0017_tbl_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newhotel'),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
